name: eurec4ahackathon
channels:
   - defaults
   - conda-forge
dependencies:
   - python
   - ipython
   - numpy
   - matplotlib
   - pandas
   - cartopy
   - xarray
   - cmocean
   - cmcrameri
   - metpy
   - gsw
   - netcdf4
   - seaborn
   - scipy
   - jupyter
   - tqdm
   - pydap
